version: "3.9"

networks:
  cloud-net:
    name: cloud-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:

  web-frontend-server:
    build: ./web-frontend-server
    image: nguyennhathao/web:dev
    container_name: web-frontend-server
    networks:
      cloud-net:
        ipv4_address: 172.18.0.2
    restart: unless-stopped

  web-frontend-server2:
    build: ./web-frontend-server
    image: hotensv/web2:dev
    container_name: web-frontend-server2
    networks:
      cloud-net:
        ipv4_address: 172.18.0.4
    restart: unless-stopped

  application-backend-server:
    build: ./application-backend-server
    image: nguyennhathao/app:dev
    container_name: application-backend-server
    networks:
      cloud-net:
        ipv4_address: 172.18.0.3
    ports: ["8085:8081"]
    environment:
      OIDC_ISSUER: "http://authentication-identity-server:8080/realms/realm_sv52300198"
      OIDC_AUDIENCE: "account"
    restart: unless-stopped

  relational-database-server:
    image: mariadb:11
    container_name: relational-database-server
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: minicloud
    volumes:
      - ./relational-database-server/init:/docker-entrypoint-initdb.d:ro
    networks:
      cloud-net:
        ipv4_address: 172.18.0.5
    ports: ["3306:3306"]
    restart: unless-stopped

  authentication-identity-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: authentication-identity-server
    command: ["start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    networks:
      cloud-net:
        ipv4_address: 172.18.0.6
    ports: ["8081:8080"]
    volumes:
      - ./authentication-identity-server/data:/opt/keycloak/data
    restart: unless-stopped

  object-storage-server:
    image: minio/minio
    container_name: object-storage-server
    command: ["server","/data","--console-address",":9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./object-storage-server/data:/data
    networks:
      cloud-net:
        ipv4_address: 172.18.0.7
    ports: ["9000:9000", "9001:9001"]
    restart: unless-stopped

  internal-dns-server:
    image: internetsystemsconsortium/bind9:9.18
    container_name: internal-dns-server
    ports:
      - "1053:53/udp"
    volumes:
      - ./internal-dns-server/named.conf:/etc/bind/named.conf:ro
      - ./internal-dns-server/named.conf.options:/etc/bind/named.conf.options:ro
      - ./internal-dns-server/named.conf.local:/etc/bind/named.conf.local:ro
      - ./internal-dns-server/db.cloud.local:/etc/bind/db.cloud.local:ro
    networks:
      cloud-net:
        ipv4_address: 172.18.0.9
    restart: unless-stopped

  monitoring-node-exporter-server:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter-server
    ports:
      - "9100:9100"
    networks:
      cloud-net:
        ipv4_address: 172.18.0.10
    restart: unless-stopped

  monitoring-prometheus-server:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus-server
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring-prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      cloud-net:
        ipv4_address: 172.18.0.11
    restart: unless-stopped

  monitoring-grafana-dashboard-server:
    image: grafana/grafana:latest
    container_name: monitoring-grafana-dashboard-server
    ports:
      - "3000:3000"
    networks:
      cloud-net:
        ipv4_address: 172.18.0.12
    restart: unless-stopped

  api-gateway-proxy-server:
    image: nginx:stable
    container_name: api-gateway-proxy-server
    depends_on:
      - web-frontend-server
      - web-frontend-server2
      - application-backend-server
      - authentication-identity-server
    networks:
      cloud-net:
        ipv4_address: 172.18.0.13
    ports: ["80:80"]
    volumes:
      - ./api-gateway-proxy-server/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  reverse-proxy-server:
    image: nginx:latest
    container_name: reverse-proxy-server
    ports:
      - "8080:80"
    volumes:
      - ./reverse-proxy-server/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-frontend-server
    networks:
      cloud-net:
        ipv4_address: 172.18.0.14
    restart: unless-stopped
